services:
  postgres-db-orthanc:
    image: postgres:16
    container_name: postgresdborthanc
    restart: always
    shm_size: 128mb
    volumes:
      - ./data/pgdata-orthanc:/var/lib/postgresql/data
    networks:
      - orthnet 
    environment:
      - POSTGRES_USER=$ORTHANC_DB_USERNAME
      - POSTGRES_PASSWORD=$ORTHANC_DB_PASSWORD
      - POSTGRES_DB=$ORTHANC_DB_NAME  # value must match orthanc.json
    profiles:
      - nginx-proxy 
      - envoy-proxy

  postgres-db-keycloak:
    image: postgres:16
    container_name: postgresdbkeycloak
    restart: always
    shm_size: 128mb
    volumes:
      - ./data/pgdata-keycloak:/var/lib/postgresql/data
    networks:
      - orthnet 
    environment:
      - POSTGRES_USER=$KEYCLOAK_DB_USERNAME
      - POSTGRES_PASSWORD=$KEYCLOAK_DB_PASSWORD
      - POSTGRES_DB=$KEYCLOAK_DB_NAME  # value must match keycloak config
    profiles:
      - nginx-proxy 
      - envoy-proxy

  orthanc-backend:
    image: $DOCKER_IMAGE_ORTHANC
    container_name: orthancbackend
    command: /run/secrets/    # Path to the configuration files (stored as secrets)
    env_file:
      - .orthanc.env # variables that are not referenced in orthanc.json can be put in this file
    environment:    # Variables referenced from orthanc.json and are used in other services, must be passed in this way from .env
      - DB_USERNAME=$ORTHANC_DB_USERNAME
      - DB_PASSWORD=$ORTHANC_DB_PASSWORD
      - DB_NAME=$ORTHANC_DB_NAME
      - DB_ADDR=$ORTHANC_DB_ADDR
    secrets:
      - orthanc.json
      - site.pem
      - serversidescript.lua
    restart: always
    volumes:
      - ./OrthancStorage:/run/secrets/OrthancStorage
    networks:
      - orthnet
    healthcheck:
      disable: true  # Healthcheck is driven by Envoy, see envoy.yaml for healthcheck configuration
    depends_on:
      - postgres-db-orthanc
    profiles:
      - nginx-proxy 
      - envoy-proxy

  nginx-proxy:
    image: $DOCKER_IMAGE_NGINX
    container_name: nginx
    ports:
      - 443:443
      - 11112:11112
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 512M
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./$SITE_KEY_CERT_FILE:/etc/nginx/conf.d/site.pem
    networks:
      - orthnet
    depends_on:
      - orthanc-backend 
    profiles:
      - nginx-proxy 

  envoy-proxy:
    image: $DOCKER_IMAGE_ENVOY 
    container_name: envoy
    ports:
      - 9901:9901
      - 443:443
      - 11112:11112
    command:
      - "-c"
      - "/etc/envoy/envoy.yaml"
      - "--log-level"
      - "info"
      - "--component-log-level"
      - "upstream:info,http:debug"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./$SITE_KEY_CERT_FILE:/etc/ssl/certs/site.pem
      - ./envoy:/home/envoy
    networks:
      - orthnet
    depends_on:
      - orthanc-backend 
    profiles:
      - envoy-proxy

secrets:
  orthanc.json:
    file: $ORTHANC_CONFIG_FILE
  site.pem:
    file: $SITE_KEY_CERT_FILE
  serversidescript.lua:
    file: $SERVER_SCRIPT_FILE
networks:
  orthnet:
    driver: bridge
    enable_ipv6: false
